# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.6

env:
  - TOXENV=django18
  - TOXENV=django111

matrix:
  include:
    - python: 3.6
      env: TOXENV=quality
    - python: 3.6
      env: TOXENV=docs

cache:
  - pip
  
before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov
